export const DISTRICTS = [
    { label: 'அரியலூர் (Ariyalur)', value: 'Ariyalur' },
    { label: 'செங்கல்பட்டு (Chengalpattu)', value: 'Chengalpattu' },
    { label: 'சென்னை (Chennai)', value: 'Chennai' },
    { label: 'கோயம்புத்தூர் (Coimbatore)', value: 'Coimbatore' },
    { label: 'கடலூர் (Cuddalore)', value: 'Cuddalore' },
    { label: 'தர்மபுரி (Dharmapuri)', value: 'Dharmapuri' },
    { label: 'திண்டுக்கல் (Dindigul)', value: 'Dindigul' },
    { label: 'ஈரோடு (Erode)', value: 'Erode' },
    { label: 'கள்ளக்குறிச்சி (Kallakurichi)', value: 'Kallakurichi' },
    { label: 'காஞ்சிபுரம் (Kanchipuram)', value: 'Kanchipuram' },
    { label: 'கன்னியாகுமரி (Kanyakumari)', value: 'Kanyakumari' },
    { label: 'கரூர் (Karur)', value: 'Karur' },
    { label: 'கிருஷ்ணகிரி (Krishnagiri)', value: 'Krishnagiri' },
    { label: 'மதுரை (Madurai)', value: 'Madurai' },
    { label: 'மயிலாடுதுறை (Mayiladuthurai)', value: 'Mayiladuthurai' },
    { label: 'நாகப்பட்டினம் (Nagapattinam)', value: 'Nagapattinam' },
    { label: 'உதகமண்டலம் (Nilgiris)', value: 'Nilgiris' },
    { label: 'நாமக்கல் (Namakkal)', value: 'Namakkal' },
    { label: 'பெரம்பலூர் (Perambalur)', value: 'Perambalur' },
    { label: 'புதுக்கோட்டை (Pudukkottai)', value: 'Pudukkottai' },
    { label: 'ராமநாதபுரம் (Ramanathapuram)', value: 'Ramanathapuram' },
    { label: 'ராணிப்பேட்டை (Ranipet)', value: 'Ranipet' },
    { label: 'சேலம் (Salem)', value: 'Salem' },
    { label: 'சிவகங்கை (Sivaganga)', value: 'Sivaganga' },
    { label: 'தென்காசி (Tenkasi)', value: 'Tenkasi' },
];
