export const OCCUPATIONS = [
    { label: 'Programmer', value: 'Programmer' },
    { label: 'Bank', value: 'Bank' },
    { label: 'Private', value: 'Private' },
    { label: 'Project Manager', value: 'Project Manager' },
    { label: 'Lecturer', value: 'Lecturer' },
    { label: 'Asst Professor', value: 'Asst Professor' },
    { label: 'Mechanical Engineer', value: 'Mechanical Engineer' },
    { label: 'Engineer Marketing', value: 'Engineer Marketing' },
    { label: 'Technical Officer', value: 'Technical Officer' },
    { label: 'Legal Services', value: 'Legal Services' },
    { label: 'Manufacturing / Distributions', value: 'Manufacturing / Distributions' },
    { label: 'Medical / Health Services', value: 'Medical / Health Services' },
    { label: 'Politics / Government / Military', value: 'Politics / Government / Military' },
    { label: 'Real Estate', value: 'Real Estate' },
    { label: 'Sales / Marketing', value: 'Sales / Marketing' },
    { label: 'Science', value: 'Science' },
    { label: 'Technical / Engineering', value: 'Technical / Engineering' },
    { label: 'Transportation', value: 'Transportation' },
    { label: 'Food Service', value: 'Food Service' },
    { label: 'Other', value: 'Other' },
    { label: 'Software Engineer', value: 'Software Engineer' },
    { label: 'No Job', value: 'NoJob' },
    { label: 'Railway Department', value: 'Railway Department' },
    { label: 'Business', value: 'Business' },
    { label: 'Civil Engineer', value: 'Civil Engineer' },
];
