export const STARS = [
    { id: 2, label: 'அஸ்வினி (Aswini)', value: 'Aswini' },
    { id: 3, label: 'பரணி (Bharani)', value: 'Bharani' },
    { id: 4, label: 'கார்த்திகை (Karthikai)', value: 'Karthikai' },
    { id: 5, label: 'ரோகிணி (Rokini)', value: 'Rokini' },
    { id: 7, label: 'மிருகசீரிடம் (Mirugaseeridam)', value: 'Mirugaseeridam' },
    { id: 8, label: 'திருவாதிரை (Thiruvathirai)', value: 'Thiruvathirai' },
    { id: 9, label: 'புனர்பூசம் (Punarpoosam)', value: 'Punarpoosam' },
    { id: 10, label: 'பூசம் (Poosam)', value: 'Poosam' },
    { id: 11, label: 'ஆயில்யம் (Aayilyam)', value: 'Aayilyam' },
    { id: 12, label: 'மகம் (Magam)', value: 'Magam' },
    { id: 13, label: 'பூரம் (Pooram)', value: 'Pooram' },
    { id: 14, label: 'உத்திரம் (Uththiram)', value: 'Uththiram' },
    { id: 15, label: 'அஸ்தம் (Astham)', value: 'Astham' },
    { id: 16, label: 'சித்திரை (Chiththirai)', value: 'Chiththirai' },
    { id: 17, label: 'சுவாதி (Chuvathi)', value: 'Chuvathi' },
    { id: 18, label: 'விசாகம் (Visagam)', value: 'Visagam' },
    { id: 19, label: 'அனுஷம் (Anusham)', value: 'Anusham' },
    { id: 20, label: 'கேட்டை (Keddai)', value: 'Keddai' },
    { id: 21, label: 'மூலம் (Moolam)', value: 'Moolam' },
    { id: 22, label: 'பூராடம் (Pooradam)', value: 'Pooradam' },
    { id: 23, label: 'உத்திராடம் (Uththiradam)', value: 'Uththiradam' },
    { id: 24, label: 'திருவோணம் (Thiruvonam)', value: 'Thiruvonam' },
    { id: 25, label: 'அவிட்டம் (Aviddam)', value: 'Aviddam' },
    { id: 26, label: 'சதயம் (Chathayam)', value: 'Chathayam' },
    { id: 27, label: 'பூரட்டாதி (Pooraddathi)', value: 'Pooraddathi' },
];
